language: python
sudo: required

python:
  - "3.8"
  
before_install:
  - cd Machine-Learning-for-Structural-Bioinformatics/PSSpred/
  
before_install:
  - sudo apt-get install liblapack-dev
  - sudo apt-get install libatlas-base-dev
  - sudo apt-get install gfortran
  - sudo apt-get install gfortran libblas-dev liblapack-dev
  - pip3 install coverage
  - pip3 install codecov
  - pip3 install -U tox-travis
  - pip3 install numpy
install:
  - |
    ls
    python3 setup.py build
    python3 setup.py sdist
    python3 setup.py bdist
    python3 setup.py bdist_egg
    python3 setup.py install
    
script:
  - git config --global user.email "ucecwme@ucl.ac.uk"
  - git config --global user.name "nickcafferry"
  - git init
  - git lfs install
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull
  - ls
  - coverage debug sys
  - coverage run pymbd/vdw_param.py
  - codecov
  - bash <(curl -s https://codecov.io/bash)
  - cd /home/travis/build/nickcafferry/Machine-Learning-in-Molecular-Sciences/Machine-Learning-for-Structural-Bioinformatics/PSSpred/
  - mkdir pr
  - cd pr/
  - wget -O nr.tar.gz https://zhanglab.ccmb.med.umich.edu/cgi-bin/download_ftp.cgi?ID=nr.tar.gz
  - tar -zxvf nr.tar.gz
  - ls
  - cd ../
  - sudo apt-get install perl
  - cd PSSpred_v4/
  - ./PSSpred.pl seq.fasta
  - ls
  - git lfs track "*.dat"
  - git add .gitattributes
  - git commit -m "track *.psd files using Git LFS"
  - git add seq.dat
  - git commit -m "Add seq.dat"
  - git add seq.dat.ss
  - git commit -m "Add seq.dat.ss" 
  - pwd
  - cd ../../../
  - git push origin master
notifications:
  email: false
