name: Build up document

on: [push, pull_request]

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:

    - name: Clone repositories
      run: |
        git clone https://github.com/nickcafferry/Machine-Learning-in-Molecular-Sciences.git manim
        cd manim/
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        ssh-keygen -t rsa -C 'ucecwme@ucl.ac.uk'
        git rm -rf 0505.xyz
        git commit -m "remove 0505.xyz"
        git push origin master
        ls
        
        echo "------------------------------------------------------\n"
        
        

    


