name: Build up document

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone repositories
      run: |
        cd ..
        mkdir quantum 
        cd quantum
        git clone -o mlms -b quantum https://github.com/nickcafferry/Machine-Learning-in-Molecular-Sciences.git master
        git clone https://github.com/qmlcode/qml.git
        rm -rf qml
        rm -rf docs
        rm README.md
        rm README.rst
        rm mkldiscover.py
        rm requirements.txt
        rm setup.py
        git remote -v
        cp -r tests/qm7/. master/Learning-Curves-Representations-and-Training-Sets/Practical-Session/Quantum-Machine-Learning/qml-tutorial-master/qm7
        git push mlms master：https://github.com/nickcafferry/Machine-Learning-in-Molecular-Sciences/tree/master
        
    


