name: Build up document

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone repositories
      run: |
        mkdir quantum 
        cd quantum/
        git clone https://github.com/qmlcode/qml.git qml
        cd qml/
        rm -rf qml
        rm -rf docs
        rm README.md
        rm README.rst
        rm mkldiscover.py
        rm requirements.txt
        rm setup.py
        cd ../../
        git clone -o orange -b quantum https://github.com/nickcafferry/Machine-Learning-in-Molecular-Sciences.git master
        cd master/Learning-Curves-Representations-and-Training-Sets/Practical-Session/Quantum-Machine-Learning/qml-tutorial-master/
        find . -name '*.xyz' | xargs rm -rfv
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: master/Learning-Curves-Representations-and-Training-Sets/Practical-Session/Quantum-Machine-Learning/qml-tutorial-master # The folder the action should deploy.
        

    


