name: Build up document

on: [push, pull_request]

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:

    - name: Clone repositories
      run: |
        mkdir quantum
        cd quantum/
        git init
        git remote add orange https://github.com/nickcafferry/Machine-Learning-in-Molecular-Sciences.git
        git remote -v
        echo "------------------------------------------------------\n"
        git branch
        echo "------------------------------------------------------\n"
        git pull orange master
        ls
        echo "------------------------------------------------------\n"
        
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git rm -rf 0505.xyz
        git commit -m "remove 0505.xyz"
        ls
        
        echo "------------------------------------------------------\n"

    - name: Deploy to GitHub pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: quantum
        FOLDER: quantum
    


