name: Build up document

on: [push, pull_request]

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:

    - name: Clone repositories
      run: |
        ls
        git init
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git rm -rf 0505.xyz
        git commit -m "remove 0505.xyz"
        git push origin master
        ls
        echo "------------------------------------------------------\n"
        
        

    


