name: Build up document

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:

    - name: Clone repositories
      run: |
        mkdir quantum
        cd quantum/
        git clone -b qml https://github.com/nickcafferry/Machine-Learning-in-Molecular-Sciences.git qml
        cd qml/
        find . -name '*.xyz' | xargs rm -rfv
        rm -rf qm7
        rm -rf master
        rm -rf quantum
        ls
        echo "------------------------------------------------------\n"
        cd ../../
        mkdir mlms
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/Machine-Learning-in-Molecular-Sciences/mlms"
        cp -r quantum/qml/. mlms

    - name: Deploy to GitHub pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: quantum
        FOLDER: mlms
    


