name: Build up document

on: [push, pull_request]

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:

    - name: Clone repositories
      run: |
        ls
        git config --global user.email "wei.mei.18@alumni.ucl.ac.uk"
        git config --global user.name "Wei Mei"
        
        git rm -rf 0505.xyz
        git rm -rf 0506.xyz
        git rm -rf 0507.xyz
        git rm -rf 0508.xyz
        git rm -rf 0509.xyz
        git rm -rf 0510.xyz
        git rm -rf 0511.xyz
        
        git commit -m "remove 0505.xyz"
        git commit -m "remove 0506.xyz"
        git commit -m "remove 0507.xyz"
        git commit -m "remove 0508.xyz"
        git commit -m "remove 0509.xyz"
        git commit -m "remove 0510.xyz"
        git commit -m "remove 0511.xyz"
        git push origin master
        ls
        echo "------------------------------------------------------\n"
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: .  # The folder the action should deploy.
        

    


