name: Build up document

on: [push, pull_request]

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone repositories
      run: |
        ls
        echo "------------------------------------------------------\n"
        find . -name '*.xyz' | xargs git rm -rf
        ls
        echo "------------------------------------------------------\n"
        git rm -rf master/*
        git rm -rf qm7/*
        echo "------------------------------------------------------\n"
        git commit
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: .  # The folder the action should deploy.
        

    


