name: Build up document

on: [push, pull_request]

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:

    - name: Clone repositories
      run: |
        ls
        git clone -o origin https://github.com/nickcafferry/Machine-Learning-in-Molecular-Sciences.git quantum
        cd quantum/
        git rm -rf 0505.xyz
        git commit -m "remove 0505.xyz"
        ls
        echo "------------------------------------------------------\n"
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: quantum # The folder the action should deploy.
        

    


