name: Build up document

on: [push, pull_request]

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone repositories
      run: |
        git config --global user.email "wei.mei.18@alumni.ucl.ac.uk"
        git config --global user.name "Wei Mei"
        ls
        echo "------------------------------------------------------\n"
        git rm -rf 0504.xyz
        git rm -rf 0505.xyz
        git rm -rf 0506.xyz
        git rm -rf 0507.xyz
        git rm -rf 0508.xyz
        git rm -rf 0509.xyz
        git rm -rf 0510.xyz
        git rm -rf 0511.xyz
        ls
        echo "------------------------------------------------------\n"
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: .  # The folder the action should deploy.
        

    


