name: Build up document

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone repositories
      run: |
        git remote add orange https://nickcafferry:732361902991@nickcafferry@github.com/nickcafferry/Machine-Learning-in-Molecular-Sciences.git
        mkdir quantum 
        cd quantum/
        git clone https://github.com/qmlcode/qml.git qml
        cd qml/
        rm -rf qml
        rm -rf docs
        rm README.md
        rm README.rst
        rm mkldiscover.py
        rm requirements.txt
        rm setup.py
        cd ../../
        git clone -b quantum https://github.com/nickcafferry/Machine-Learning-in-Molecular-Sciences.git master
        git remote -v
        git branch
        cp -r quantum/qml/tests/qm7/. master/Learning-Curves-Representations-and-Training-Sets/Practical-Session/Quantum-Machine-Learning/qml-tutorial-master/qm7
        git push orange master : origin/master

    


