name: PSSpred

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: Protein Secondary Structure prediction

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd Machine-Learning-for-Structural-Bioinformatics/

        cd PSSpred/
        
        mkdir nr
        cd nr/
        wget -O nr.tar.gz https://zhanglab.ccmb.med.umich.edu/cgi-bin/download_ftp.cgi?ID=nr.tar.gz
        tar -zxvf nr.tar.gz
        echo "Done with downloading and extracting nr!"
        git add -A
        git commit -m "Add nr.tar.gz"
        cd ../../../
        git push origin master
